#!/bin/sh

LUPDATE_OPTIONS="-no-obsolete"
LUPDATE_OPTIONS="${LUPDATE_OPTIONS} -locations none "
TS_FILE="../translations/src.flacon.ts"


PATH=${PATH}:/opt/homebrew/Cellar/qt@5/5.15.2/bin

[ -z "${LUPDATE}" ] && LUPDATE=$(which lupdate-qt6 2>/dev/null)
[ -z "${LUPDATE}" ] && LUPDATE=$(which lupdate-qt5 2>/dev/null)
[ -z "${LUPDATE}" ] && LUPDATE=$(which lupdate-qt4 2>/dev/null)
[ -z "${LUPDATE}" ] && LUPDATE=$(which lupdate 2>/dev/null)

if [ -z "${LUPDATE}" ]; then
    echo "The lupdate program not found."
    exit 1;
fi

${LUPDATE} ${LUPDATE_OPTIONS} .. -ts ${TS_FILE}


