on: [push, pull_request]

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: bullseye
    steps:
      - name: Set env
        run: |
          echo "RELEASE_DATE=$(date +%Y.%m.%d_%H.%M.%S)" >> ${GITHUB_ENV}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

          [[ "${GITHUB_REF_TYPE}"  = "tag" ]] && echo APPIMAGE_NAME="flacon-${GITHUB_REF_NAME:1}-x86_64.AppImage" >> $GITHUB_ENV
          [[ "${GITHUB_REF_TYPE}" != "tag" ]] && echo APPIMAGE_NAME="flacon-$(date +%Y.%m.%d_%H.%M.%S)-x86_64.AppImage" >> $GITHUB_ENV

          echo "==============================="
          export
          echo "-------------------------------"
          cat $GITHUB_ENV
          echo "==============================="
          ls -l ${GITHUB_ENV}

      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            apt-get -y update && \
            apt-get -y install \
                build-essential \
                pkg-config \
                cmake \
                qtbase5-dev \
                qttools5-dev-tools \
                qttools5-dev \
                libuchardet-dev \
                libtag1-dev \
                desktop-file-utils


          # Produce a binary artifact and place it in the mounted volume
          run: |
            echo "==============================="
            ls -lh /etc/apt/
            echo "==============================="
            apt-get -y update && apt-get -y install \
                flac \
                mac \
                alacenc \
                vorbis-tools \
                wavpack \
                lame \
                ttaenc \
                faac \
                opus-tools \
                sox


            pwd
            ls

            # mount
            # echo "==============================="
            # export
            # echo "-------------------------------"
            # cat ${GITHUB_ENV}
            # echo "==============================="

            # cp $(which git) "/artifacts/${artifact_name}"
            # echo "Produced artifact at /artifacts/${artifact_name}"

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
