name: Build Legacy Flacon

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string

env:
  BREW_DIR:         /opt/flacon-homebrew/${{ inputs.arch }}
  ARM_BREW_DIR:     /opt/flacon-homebrew/arm64
  X86_BREW_DIR:     /opt/flacon-homebrew/x86_64
  FLACON_PROGRAMS:  flacon-programs-${{ inputs.arch }}
  BUNDLE_DIR:       ${{github.workspace}}/build/Flacon.app
  PREFIX:           ${{ github.workspace }}/build/usr/

  OSX_DEPLOYMENT_TARGET: "10.15"

  TAGLIB_VERSION:       "2.3.1"
  UCHARDET_VERSION:     "0.0.8"
  SPARKLE_VERSION:      "1.26.0"

jobs:
  build-legacy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6


    ###################################
    #
    - name: Prepare
      run: |
        if [ "${{ inputs.arch }}" = "x86_64" ]; then
          export "HOST=x86_64-apple-darwin"
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          export "HOST=aarch64-apple-darwin"
        fi
        echo "HOST=${HOST}" >> $GITHUB_ENV

        export
        mkdir -p "${{ env.PREFIX }}"
        mkdir -p "${{ env.BUNDLE_DIR }}/Contents/MacOS"

    # - name: Install tools
    #   shell: bash
    #   run: |
    #     git clone https://github.com/flacon/flacon.third-party.git ${HOME}/flacon.third-party
    #     mkdir -p ${HOME}/bin/
    #     cp ${HOME}/flacon.third-party/bin/* ${HOME}/bin/

    - name: Install homebrew arm64
      shell: bash
      run: |
        curl -s -L https://github.com/flacon/flacon.third-party/releases/download/v0.1/flacon-homebrew-arm64.tgz > ${HOME}/flacon-homebrew-arm64.tgz
        sudo tar xf ${HOME}/flacon-homebrew-arm64.tgz -C /


    - name: Install homebrew x86_64
      shell: bash
      run: |
        curl -s -L https://github.com/flacon/flacon.third-party/releases/download/v0.1/flacon-homebrew-x86_64.tgz > ${HOME}/flacon-homebrew-x86_64.tgz
        sudo tar xf ${HOME}/flacon-homebrew-x86_64.tgz -C /


    - name: Fixing homebrew Qt binaries
      shell: bash
      run: |
        rm -rf ${ARM_BREW_DIR}/opt/qt5/bin/
        ln -s ${X86_BREW_DIR}/opt/qt5/bin/ ${ARM_BREW_DIR}/opt/qt5/bin

    ###################################
    #
    - name: Build uchardet
      working-directory: ${{ env.PREFIX }}
      run: |
          git clone --depth 1 https://gitlab.freedesktop.org/uchardet/uchardet.git --branch v${{env.UCHARDET_VERSION}} uchardet
          cmake -S uchardet -B uchardet/build \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
            -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.OSX_DEPLOYMENT_TARGET }} \
            -DBUILD_BINARY=OFF
          cmake --build uchardet/build -j$(sysctl -n hw.ncpu)
          cmake --install uchardet/build


    ###################################
    #
    - name: Build taglib
      working-directory: ${{ env.PREFIX }}
      run: |
          git clone --depth 1 https://github.com/taglib/taglib.git --branch v${{env.TAGLIB_VERSION}} taglib
          cd taglib && git submodule update --init --recursive && cd ..
          cmake -S taglib -B taglib/build \
            -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
            -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.OSX_DEPLOYMENT_TARGET }} \
            -DBUILD_SHARED_LIBS=ON
          cmake --build taglib/build -j$(sysctl -n hw.ncpu)
          cmake --install taglib/build


   ###################################
    #
    - name: Install FFAudio
      run: |
        git clone  --depth 1 https://github.com/SokoloffA/FFAudio.git -b flacon FFAudio
        mkdir -p ${HOME}/Library/Frameworks
        cp -a FFAudio/FFAudio.xcframework/macos-arm64_x86_64/FFAudio.framework ${HOME}/Library/Frameworks


    ###################################
    #
    - name: Install Saprkle
      shell: bash
      run: |
        curl -s -L https://github.com/sparkle-project/Sparkle/releases/download/${{env.SPARKLE_VERSION}}/Sparkle-${{env.SPARKLE_VERSION}}.tar.xz > ${HOME}/Sparkle.tar.xz
        mkdir -p ${HOME}/Library/Frameworks
        tar xf ${HOME}/Sparkle.tar.xz -C ${HOME}/Library/Frameworks Sparkle.framework


    ###################################
    #
    - name: Build Flacon
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        #export PKG_CONFIG_PATH="${BREW_DIR}/lib/pkgconfig"
        export PKG_CONFIG_PATH="${{ env.PREFIX }}/lib/pkgconfig:${{ env.PREFIX }}/share/pkgconfig"
        QT_ROOT_DIR=${BREW_DIR}/opt/qt5/lib/cmake

        echo "*******************************"
        echo "QT_ROOT_DIR: '${QT_ROOT_DIR}'"
        echo "FFAUDIO DIR: '${FFAUDIO_DIR}'"
        echo "*******************************"

        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTS=No \
          -DMAC_BUNDLE=Yes \
          -DUSE_QT5=ON \
          -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR};${{ env.PREFIX }}" \
          -DCMAKE_FRAMEWORK_PATH="${{ env.FFAUDIO_DIR }}" \
          -DCMAKE_INSTALL_PREFIX=build \
          -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
          -Bbuild \
          ${{github.workspace}}

        make -Cbuild -j 8
        make -Cbuild install


    # - name: Copy third-party binaries and libraries
    #   shell: bash
    #   working-directory: ${{github.workspace}}
    #   run: |
    #     curl -s -L https://github.com/flacon/flacon.third-party/releases/download/v0.1/flacon-programs-${{inputs.arch}}.tgz > ${HOME}/flacon-programs-${{inputs.arch}}.tgz
    #     sudo tar xf ${HOME}/flacon-programs-${{inputs.arch}}.tgz -C ${BUNDLE_DIR}/Contents --strip 1

    ###################################
    #
    - name: Check libraries
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        "${{github.workspace}}/.github/workflows/macdeploy.py" check-libs "${{ env.BUNDLE_DIR }}"


    ###################################
    #
    - name: Prepare artifacts
      run : |
        tar -C ${{github.workspace}}/build -cf ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar Flacon.app


    ###################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: Flacon-${{ inputs.arch }}
        path: ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar



    # - name: Check libraries
    #   shell: bash
    #   working-directory: ${{github.workspace}}
    #   run: |
    #     ${HOME}/bin/macdeploy.py check-libs ${BUNDLE_DIR}/


    # - name: Prepare artifacts
    #   run : |
    #     tar -C ${{github.workspace}}/build -cf ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar Flacon.app

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v7
    #   with:
    #     name: Flacon-Legacy-${{ inputs.arch }}
    #     path: ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar
