name: Build Flacon

on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      osx_target:
        type: string
        default: "10.15"

env:
  FLACON_PROGRAMS:  flacon-programs-${{ inputs.arch }}
  BUNDLE_DIR:       ${{github.workspace}}/build/Flacon.app
  BUILD_DIR:        ${{github.workspace}}/build/
  PREFIX:           ${{ github.workspace }}/build/usr/

  OSX_DEPLOYMENT_TARGET: "10.15"

  QT_VERSION:           "6.10.3"
  TAGLIB_VERSION:       "2.3.1"
  UCHARDET_VERSION:     "0.0.8"
  SPARKLE_VERSION:      "1.26.0"



jobs:
  ###################################
  build-alacenc:
    uses: ./.github/workflows/extprograms-build-alacenc.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-faac:
    uses: ./.github/workflows/extprograms-build-faac.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-flac:
    uses: ./.github/workflows/extprograms-build-flac.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-lame:
    uses: ./.github/workflows/extprograms-build-lame.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-monkeyaudio:
    uses: ./.github/workflows/extprograms-build-monkeyaudio.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-vorbis-tools:
    uses: ./.github/workflows/extprograms-build-vorbis-tools.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-opus-tools:
    uses: ./.github/workflows/extprograms-build-opus-tools.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-sox:
    uses: ./.github/workflows/extprograms-build-sox.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-ttaenc:
    uses: ./.github/workflows/extprograms-build-ttaenc.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  build-wavpack:
    uses: ./.github/workflows/extprograms-build-wavpack.yml
    with:
      arch: ${{ inputs.arch }}
      osx_target: ${{ inputs.osx_target }}

  ###################################
  #
  build-Flacon:
    runs-on: macos-latest

    needs:
      - build-alacenc
      - build-faac
      - build-flac
      - build-lame
      - build-monkeyaudio
      - build-vorbis-tools
      - build-opus-tools
      - build-sox
      - build-ttaenc
      - build-wavpack

    steps:
    - uses: actions/checkout@v6


    ###################################
    #
    - name: Prepare
      run: |
        if [ "${{ inputs.arch }}" = "x86_64" ]; then
          export "HOST=x86_64-apple-darwin"
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          export "HOST=aarch64-apple-darwin"
        fi
        echo "HOST=${HOST}" >> $GITHUB_ENV

        export
        mkdir -p "${{ env.PREFIX }}"
        mkdir -p "${{ env.BUNDLE_DIR }}/Contents/MacOS"



    ###################################
    #
    - name: Check license
      run: ./scripts/checkLicense.sh .


    ###################################
    #
    - name: Install Qt ${{ env.QT_VERSION }}
      run: |
        pip install aqtinstall
        echo "** Qt versions ****************************"
        aqt list-qt mac desktop
        echo "*******************************************"
        aqt list-qt mac desktop --modules ${{ env.QT_VERSION }} clang_64
        aqt install-qt mac desktop ${{ env.QT_VERSION }} -O "${{ env.PREFIX }}/qt"


    ###################################
    #
    - name: Download FFAudio
      run: |
        git clone  --depth 1 https://github.com/SokoloffA/FFAudio.git FFAudio
        echo "FFAUDIO_DIR=${{ runner.temp }}/FFAudio" >> $GITHUB_ENV


    ###################################
    #
    - name: Build uchardet
      working-directory: ${{ env.PREFIX }}
      run: |
          git clone --depth 1 https://gitlab.freedesktop.org/uchardet/uchardet.git --branch v${{env.UCHARDET_VERSION}} uchardet
          cmake -S uchardet -B uchardet/build \
            -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
            -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
            -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.OSX_DEPLOYMENT_TARGET }} \
            -DBUILD_BINARY=OFF
          cmake --build uchardet/build -j$(sysctl -n hw.ncpu)
          cmake --install uchardet/build


    ###################################
    #
    - name: Build taglib
      working-directory: ${{ env.PREFIX }}
      run: |
          git clone --depth 1 https://github.com/taglib/taglib.git --branch v${{env.TAGLIB_VERSION}} taglib
          cd taglib && git submodule update --init --recursive && cd ..
          cmake -S taglib -B taglib/build \
            -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
            -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.OSX_DEPLOYMENT_TARGET }} \
            -DBUILD_SHARED_LIBS=ON
          cmake --build taglib/build -j$(sysctl -n hw.ncpu)
          cmake --install taglib/build


    ###################################
    #
    - name: Install Saprkle
      shell: bash
      run: |
        curl -s -L https://github.com/sparkle-project/Sparkle/releases/download/${{env.SPARKLE_VERSION}}/Sparkle-${{env.SPARKLE_VERSION}}.tar.xz > ${HOME}/Sparkle.tar.xz
        mkdir -p ${HOME}/Library/Frameworks
        tar xf ${HOME}/Sparkle.tar.xz -C ${HOME}/Library/Frameworks Sparkle.framework


    ###################################
    #
    - name: Build Flacon
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        export PKG_CONFIG_PATH="${{ env.PREFIX }}/lib/pkgconfig:${{ env.PREFIX }}/share/pkgconfig"
        #QT_CMAKE_DIR=$(find "${{ env.PREFIX }}/qt" -name "Qt6Config.cmake" -exec dirname {} \;)
        QT_ROOT_DIR=$(find "${{ env.PREFIX }}/qt" -name "Qt6Config.cmake" | sed 's|/lib/cmake/Qt6/Qt6Config.cmake||')
        echo "*******************************"
        echo "QT_ROOT_DIR:  '${QT_ROOT_DIR}'"
        echo "$FFAUDIO DIR: '${FFAUDIO_DIR}'"
        echo "*******************************"

        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTS=No \
          -DMAC_BUNDLE=Yes \
          -DCMAKE_PREFIX_PATH="${QT_ROOT_DIR};${{ env.PREFIX }}" \
          -DCMAKE_FRAMEWORK_PATH="${{ env.FFAUDIO_DIR }}" \
          -DCMAKE_INSTALL_PREFIX=build \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.OSX_DEPLOYMENT_TARGET }} \
          -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
          -DOPENGL_agl_LIBRARY="" \
          -Bbuild \
         ${{github.workspace}}


        echo "== macdelopy.cmake ======================"
        cat  "build/macdelopy.cmake"
        echo "== cmake_install.cmake =================="
        cat  "build/cmake_install.cmake"
        echo "========================================="

        cmake --build build -j$(sysctl -n hw.ncpu)
        cmake --install build


    ###################################
    #
    - name: Download external programs
      uses: actions/download-artifact@v8
      with:
        pattern: ext-*-${{ inputs.arch }}
        path: ${{ env.BUNDLE_DIR }}/Contents/MacOS
        merge-multiple: true

    ###################################
    #
    - name: Fix and check external programs
      working-directory: ${{env.BUNDLE_DIR}}
      run: |
        chmod a+x "Contents/MacOS/"*

        echo "========================================="
        file "Contents/MacOS/"*
        otool -L "Contents/MacOS/"*

        echo "========================================="
        file "Contents/Frameworks/"*


    ###################################
    #
    - name: Check libraries
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        "${{github.workspace}}/.github/workflows/macdeploy.py" check-libs "${{ env.BUNDLE_DIR }}"


    ###################################
    #
    - name: Prepare artifacts
      run : |
        tar -C ${{github.workspace}}/build -cf ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar Flacon.app


    ###################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: Flacon-${{ inputs.arch }}
        path: ${{github.workspace}}/Flacon-${{ inputs.arch }}.tar
