on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      osx_target:
        required: true
        type: string

env:
  PREFIX: "${{ github.workspace }}/build/usr"

jobs:
  lame:
    runs-on: macos-latest

    steps:

    ##################################
    #
    - name: prepare
      run: |
        if [ "${{ inputs.arch }}" = "x86_64" ]; then
          export "HOST=x86_64-apple-darwin"
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          export "HOST=aarch64-apple-darwin"
        fi
        echo "HOST=${HOST}" >> $GITHUB_ENV

        export


    ###################################
    #
    - name: Build lame
      shell: bash
      env:
        VERSION: "4.0"

      run: |
        mkdir -p lame
        curl -sSL "https://downloads.sourceforge.net/project/lame/lame/${{ env.VERSION }}/lame-${{ env.VERSION }}.tar.gz" | tar xz --strip-components=1 -C lame
        cd lame

        # from https://github.com/Homebrew/homebrew-core/blob/main/Formula/l/lame.rb
        # LAME still calls undeclared legacy ID3 APIs, which do not compile as C23.
        # https://sourceforge.net/p/lame/bugs/517/
        # ENV["ac_cv_prog_cc_c23"] = "no"
        # ENV.append_to_cflags "-Wno-implicit-function-declaration"


        ./configure \
          ac_cv_prog_cc_c23=no \
          --host="${{ env.HOST }}" \
          --prefix="${{ env.PREFIX }}" \
          --enable-static \
          --disable-shared \
          --disable-gtktest \
          --disable-decoder \
          --enable-nasm \
          CPPFLAGS="-include locale.h" \
          CFLAGS="-arch ${{ inputs.arch }} -mmacosx-version-min=${{ inputs.osx_target }} -Wno-implicit-function-declaration" \
          LDFLAGS="-arch ${{ inputs.arch }}"


        make -j$(sysctl -n hw.ncpu)
        make install


    ##################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ext-${{ github.job }}-${{ inputs.arch }}
        path: |
          ${{ env.PREFIX }}/bin/lame
