on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      osx_target:
        required: true
        type: string

env:
  PREFIX: "${{ github.workspace }}/build/usr"

jobs:
  ttaenc:
    runs-on: macos-latest

    steps:

    ##################################
    #
    - name: prepare
      run: |
        if [ "${{ inputs.arch }}" = "x86_64" ]; then
          export "HOST=x86_64-apple-darwin"
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          export "HOST=aarch64-apple-darwin"
        fi
        echo "HOST=${HOST}" >> $GITHUB_ENV

        export
        mkdir -p  "${{ env.PREFIX }}/bin/"


    ##################################
    #
    - name: Build ttaenc
      shell: bash
      run: |
        git clone --depth 1 https://github.com/SokoloffA/ttaenc.git ttaenc || true
        cd ttaenc

        make -j$(sysctl -n hw.ncpu) \
          CC=clang \
          CFLAGS="-arch ${{ inputs.arch }} -mmacosx-version-min=${{ inputs.osx_target }} -O3 -Wall" \
          LDFLAGS="-arch ${{ inputs.arch }}"


        install -m 755 ttaenc "${{ env.PREFIX }}/bin/"


    ##################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ext-${{ github.job }}-${{ inputs.arch }}
        path: |
          ${{ env.PREFIX }}/bin/ttaenc
