on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      osx_target:
        required: true
        type: string

env:
  PREFIX: "${{ github.workspace }}/build/usr"

jobs:
  monkeyaudio:
    runs-on: macos-latest

    steps:

    ##################################
    #
    - name: prepare
      run: |
        if [ "${{ inputs.arch }}" = "x86_64" ]; then
          export "HOST=x86_64-apple-darwin"
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          export "HOST=aarch64-apple-darwin"
        fi
        echo "HOST=${HOST}" >> $GITHUB_ENV

        export


    ###################################
    #
    - name: Build mac
      shell: bash
      run: |
        git clone --depth 1 https://github.com/SokoloffA/monkeyaudio.git mac || true
        cd mac

        ./configure \
          --host="${{ env.HOST }}" \
          --prefix="${{ env.PREFIX }}" \
          --mandir=/usr/share/man \
          --infodir=/usr/share/info \
          --enable-static \
          --disable-shared \
          --enable-assembly=yes \
          CFLAGS="-arch ${{ inputs.arch }} -mmacosx-version-min=${{ inputs.osx_target }} -Wno-implicit-function-declaration" \
          CXXFLAGS="-arch ${{ inputs.arch }} -mmacosx-version-min=${{ inputs.osx_target }}" \
          LDFLAGS="-arch ${{ inputs.arch }}"

        make -j$(sysctl -n hw.ncpu)
        make install


    ##################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ext-${{ github.job }}-${{ inputs.arch }}
        path: |
          ${{ env.PREFIX }}/bin/mac
