on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
      osx_target:
        required: true
        type: string

env:
  PREFIX: "${{ github.workspace }}/build/usr"


jobs:
  flac:
    runs-on: macos-latest

    steps:

    ##################################
    #
    - name: prepare
      run: |
        export


    ##################################
    #
    - name: build
      shell: bash
      env:
        VERSION: "1.5.0"
      run: |
        git clone --depth 1 https://github.com/xiph/flac.git --branch ${{ env.VERSION }} flac || true
        cd flac
        cmake -S flac -B flac/build \
          -DCMAKE_INSTALL_PREFIX="${{ env.PREFIX }}" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_OSX_ARCHITECTURES=${{ inputs.arch }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ inputs.osx_target }} \
          -DBUILD_PROGRAMS=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_TESTING=OFF \
          -DBUILD_DOCS=OFF \
          -DBUILD_CXXLIBS=OFF \
          -DINSTALL_MANPAGES=OFF \
          -DCMAKE_DISABLE_FIND_PACKAGE_Intl=TRUE \
          -DWITH_OGG=OFF \
          -Bbuild \
          .

        cmake --build build -j$(sysctl -n hw.ncpu)
        cmake --install build
        echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
        ls "${{ env.PREFIX }}/bin/flac"

    ##################################
    #
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ext-${{ github.job }}-${{ inputs.arch }}
        path: |
          ${{ env.PREFIX }}/bin/flac
